version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:2.2
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: EnqueteApi
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: EnqueteApi
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: EnqueteApi.Test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t EnqueteApi .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker tag boku herocod3r/EnqueteApi
            docker push herocod3r/EnqueteApi